[package]
name = "djikstra"
version = "0.1.0"
edition = "2021"
authors = [
        "Pranjal Rastogi <pranjal.rastogi@plaksha.edu.in>",
        "Arbaaz Shafiq <arbaazshafiq@gmail.com>",
]
description = """Implements Djikstra's algorithm for finding the shortest path in a graph in Rust."""

[dependencies]
